<?php
/**
 * Copyright (c) 2018 - present
 * Google Maps PHP - ViewportTest.php
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 5/9/2018
 * MIT license: https://github.com/biscolab/google-maps-php/blob/master/LICENSE
 */

namespace Biscolab\GoogleMaps\Tests\Object;

use Biscolab\GoogleMaps\Fields\LatLngBoundsFields;
use Biscolab\GoogleMaps\Fields\LatLngFields;
use Biscolab\GoogleMaps\Object\LatLng;
use Biscolab\GoogleMaps\Object\LatLngBounds;
use Biscolab\GoogleMaps\Object\Viewport;
use Biscolab\GoogleMaps\Tests\TestCase;

/**
 * Class ViewportTest
 * @package Biscolab\geocode\Tests
 */
class ViewportTest extends TestCase
{

	/**
	 * @var LatLngBounds
	 */
	private $viewport;

	public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
	{

		parent::setUp(); // TODO: Change the autogenerated stub

		$this->viewport = new Viewport();
	}

	/**
	 * @test
	 */
	public function testViewportSetterGetter()
	{

		$viewport = $this->viewport;

		$southwest = new LatLng([
			LatLngFields::LAT => 20.89,
			LatLngFields::LNG => -40.82,
		]);

		$northeast = new LatLng([
			LatLngFields::LAT => 22.73,
			LatLngFields::LNG => 3.6370,
		]);

		$viewport->setSouthwest($southwest);
		$viewport->setNortheast($northeast);

		$this->assertEquals(new Viewport([
			LatLngBoundsFields::SOUTHWEST => [
				LatLngFields::LAT => 20.89,
				LatLngFields::LNG => -40.82,
			],
			LatLngBoundsFields::NORTHEAST => [
				LatLngFields::LAT => 22.73,
				LatLngFields::LNG => 3.6370,
			],
		]), $viewport);

	}
}
